# This file was generated by GoReleaser. DO NOT EDIT.
cask "protect" do
  name "protect"
  desc "UniFi Protect View Switcher CLI"
  homepage "https://github.com/methridge/protect"
  version "1.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "protect"

  on_macos do
    on_intel do
      url "https://github.com/methridge/protect/releases/download/v#{version}/protect_Darwin_x86_64.tar.gz"
      sha256 "455054f80404fa006ff5247230a5079d65a6836735ab2c11b774d8cd1371a8c1"
    end
    on_arm do
      url "https://github.com/methridge/protect/releases/download/v#{version}/protect_Darwin_arm64.tar.gz"
      sha256 "b2ce17fbdce9db5c660b82ae7fc663d0a4132902288093ce2cea7c83934d04c0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/methridge/protect/releases/download/v#{version}/protect_Linux_x86_64.tar.gz"
      sha256 "bd77e0a5b00eedbd209424fc05b412599e11d423f39fe5a16a868abe7e06e8b4"
    end
    on_arm do
      url "https://github.com/methridge/protect/releases/download/v#{version}/protect_Linux_arm64.tar.gz"
      sha256 "d70011dd648fa7f66de630c0cfa7649f26c53e43a0b2da73fa9b30639b5c6423"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/protect"]
    end
  end

  # No zap stanza required
end
