# This file was generated by GoReleaser. DO NOT EDIT.
cask "protect" do
  name "protect"
  desc "UniFi Protect View Switcher CLI"
  homepage "https://github.com/methridge/protect"
  version "1.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "protect"

  on_macos do
    on_intel do
      url "https://github.com/methridge/protect/releases/download/v#{version}/protect_Darwin_x86_64.tar.gz"
      sha256 "97d12620eb929e381f725f0e9841604dff708b9279c057c8f2435122e5358fb4"
    end
    on_arm do
      url "https://github.com/methridge/protect/releases/download/v#{version}/protect_Darwin_arm64.tar.gz"
      sha256 "e744098e956e956505df8ae2870f2b37a213b06bfe01d070b5ba1e34f94b73b4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/methridge/protect/releases/download/v#{version}/protect_Linux_x86_64.tar.gz"
      sha256 "17b37295724a9c9595acf87a52bbaecca10d5a5e032700fccab7ff27e91733c8"
    end
    on_arm do
      url "https://github.com/methridge/protect/releases/download/v#{version}/protect_Linux_arm64.tar.gz"
      sha256 "5f1678edfe2eb4fff6f0f0f2618163dea2cf8c3b09d3f3d623eb082a4af0cabb"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/protect"]
    end
  end

  # No zap stanza required
end
