# This file was generated by GoReleaser. DO NOT EDIT.
cask "protect" do
  name "protect"
  desc "UniFi Protect View Switcher CLI"
  homepage "https://github.com/methridge/protect"
  version "1.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "protect"

  on_macos do
    on_intel do
      url "https://github.com/methridge/protect/releases/download/v#{version}/protect_Darwin_x86_64.tar.gz"
      sha256 "b2826fc1b6ec04d200152dc91d75ad89c1b1f9cadc00f27573956b1ba3be10a1"
    end
    on_arm do
      url "https://github.com/methridge/protect/releases/download/v#{version}/protect_Darwin_arm64.tar.gz"
      sha256 "777a42ed1ee270f07167cc76785cb952adf75f1c184c2fabae89529019985dbd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/methridge/protect/releases/download/v#{version}/protect_Linux_x86_64.tar.gz"
      sha256 "fc99561354dad3253737502e4053cd5e1a25f3c22d69c0bcafb539faa889d7ae"
    end
    on_arm do
      url "https://github.com/methridge/protect/releases/download/v#{version}/protect_Linux_arm64.tar.gz"
      sha256 "2e85ed303c0bcc335524d5e97b2e22bfbab19b836a952ccf6290a923a9530a8d"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/protect"]
    end
  end

  # No zap stanza required
end
