# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Protect < Formula
  desc "UniFi Protect View Switcher CLI"
  homepage "https://github.com/methridge/protect"
  version "1.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/methridge/protect/releases/download/v1.3.0/protect_Darwin_x86_64.tar.gz"
      sha256 "8700e2dc1f60f2b3312e15fce477d2830dc7d7a28d79ef8198161c72ee91a6dc"

      def install
        bin.install "protect"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/methridge/protect/releases/download/v1.3.0/protect_Darwin_arm64.tar.gz"
      sha256 "d6dee0e56bb9202c9f8f90431ea1ee97307cc21f6786b4f5cb34336b0804b42c"

      def install
        bin.install "protect"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/methridge/protect/releases/download/v1.3.0/protect_Linux_x86_64.tar.gz"
      sha256 "566a43a973ef008ada811f5de26f4f35efab0877fc0f4a1f24d29f237c19f702"
      def install
        bin.install "protect"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/methridge/protect/releases/download/v1.3.0/protect_Linux_arm64.tar.gz"
      sha256 "f843eaeed262ab537c684123744ef095e9f36473bd15211d0d59f0df49e0fdd4"
      def install
        bin.install "protect"
      end
    end
  end
end
